name: easyportuguese

description: A new Flutter project.
# Reuse for all
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: 1.5.0
  package_info_plus: ^8.3.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  device_info_plus: ^10.1.0
  shorebird_code_push: ^2.0.4
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.0
  shared_preferences: ^2.5.4
  firebase_analytics: ^10.10.7




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  